name: Rye Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash

      - name: Add Rye to PATH (Linux/macOS)
        if: runner.os != 'Windows'
        run: echo 'source "$HOME/.rye/env"' >> ~/.bashrc

      - name: Add Rye to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo 'source "$HOME/.rye/env"' >> $env:GITHUB_PATH

      - name: Sync Rye
        run: rye sync

      - name: Run pytest with Rye
        run: rye run pytest
